# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

{{% if product == 'slmicro6' %}}
{{% set login_defs_path = "/usr/etc/login.defs" %}}
{{% else %}}
{{% set login_defs_path = "/etc/login.defs" %}}
{{% endif %}}

{{{ ansible_set_config_file(msg='Ensure new users receive home directories', file=login_defs_path, parameter="CREATE_HOME", value='yes', create='yes', rule_title=rule_title) }}}
