# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol,multi_platform_almalinux
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- name: "Disable WiFi Network Notification in GNOME3"
  community.general.ini_file:
    dest: /etc/dconf/db/local.d/00-security-settings
    section: org/gnome/nm-applet
    option: suppress-wireless-networks-available
    value: "true"
    create: yes
    no_extra_spaces: yes
  register: result_ini

- name: "Prevent user modification of GNOME3 disablement of WiFi"
  ansible.builtin.lineinfile:
    path: /etc/dconf/db/local.d/locks/00-security-settings-lock
    regexp: '^/org/gnome/nm-applet/suppress-wireless-networks-available$'
    line: '/org/gnome/nm-applet/suppress-wireless-networks-available'
    create: yes
  register: result_lineinfile

- name: Dconf Update
  ansible.builtin.command: dconf update
  when: result_ini is changed or result_lineinfile is changed
