# platform = multi_platform_all
# reboot = false
# complexity = low
# strategy = configure
# disruption = low

{{{ ansible_instantiate_variables("var_tftpd_secure_directory") }}}

-   name: "{{{ rule_title }}} - Check if tftp.service exists"
    ansible.builtin.stat:
        path: "/usr/lib/systemd/system/tftp.service"
    register: tftp_service_file

-   name: "{{{ rule_title }}} - Ensure ExecStart includes secure directory"
    community.general.ini_file:
        path: "/usr/lib/systemd/system/tftp.service"
        section: Service
        option: ExecStart
        value: "/usr/sbin/in.tftpd -s {{ var_tftpd_secure_directory }}"
        state: present
    when: tftp_service_file.stat.exists

-   name: "{{{ rule_title }}} - Reload systemd manager configuration"
    ansible.builtin.command: systemctl daemon-reload
    when: tftp_service_file.stat.exists

-   name: "{{{ rule_title }}} - Restart tftp service to apply changes"
    ansible.builtin.service:
        name: tftp
        state: restarted
        enabled: yes
    when: tftp_service_file.stat.exists
