# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: {{{ rule_title }}} - Get interactive users from passwd file
  ansible.builtin.getent:
    database: passwd
  register: passwd_entries

- name: {{{ rule_title }}} - Create list of interactive users with UID and home directory
  ansible.builtin.set_fact:
    interactive_users: "{{ interactive_users | default([]) + [{'uid': item.value[1], 'home': item.value[4], 'username': item.key}] }}"
  loop: "{{ passwd_entries.ansible_facts.getent_passwd | dict2items }}"
  when:
    - item.value[1] | int >= {{{ uid_min }}} | int
    - item.value[1] | int != {{{ nobody_uid }}} | int
    - item.value[4] != ""

- name: {{{ rule_title }}} - Find dot files in interactive user home directories
  ansible.builtin.find:
    paths: "{{ item.home }}"
    patterns: ".*"
    file_type: file
    hidden: yes
    depth: 1
    follow: no
  register: user_dotfiles
  loop: "{{ interactive_users | default([]) }}"
  failed_when: false
  when: item.home != ""

- name: {{{ rule_title }}} - Set correct ownership for user initialization files
  ansible.builtin.file:
    path: "{{ item.1.path }}"
    owner: "{{ item.0.item.username }}"
    follow: no
  loop: "{{ user_dotfiles.results | subelements('files', skip_missing=True) }}"
  when:
    - item.0 is not skipped
    - item.1.path is defined
