# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low

{{{ ansible_set_config_file(file="/etc/aliases",
                            parameter='postmaster',
                            separator=': ',
                            separator_regex='\s*:\s*',
                            value='root',
                            create='yes',
                            register='aliases_postmaster_changed',
                            rule_title=rule_title) }}}

- name: {{{ rule_title }}} - Check if newaliases command is available
  ansible.builtin.stat:
    path: /usr/bin/newaliases
  register: result_newaliases_present

- name: {{{ rule_title }}} - Update postfix aliases
  ansible.builtin.command:
    cmd: newaliases
  when:
    - result_newaliases_present.stat.exists
    - aliases_postmaster_changed is changed

